### ISSUE TITLE
Fetch notification data when app is closed?

### ISSUE THREAD

**Issue by greenreptile** [pusheco/pushe-android-studio-sample#51]
Hi there

Through below listener, I can fetch data from notification in pushe :

```java
Pushe.getPusheService(PusheNotification.class).setNotificationListener(new PusheNotificationListener() {

@Override
            public void onCustomContentNotification(@NonNull Map<String, Object> customContent) {

            }
});
```

But when application isn't in memory (is closed), no event triggered eventually (just app opened). 
Is there any solution to cover this situation? because **I want to start some intents when user touched the push notification bar even when app is closed completely.** 

Thank you in advanced

**Comment by greenreptile** [comment]
And if json is the answer, any java sample code would be helpful really . There isn't any document on pushe.co and I don't know why!

**Comment by mahdi-malv** [comment]
Hey

When a push notification is received (app is in 'closed' state), the application class starts and calls `onCreate`. The notification events are called after this event. So:

```
Push received -> Application#onCreate is called -> Pushe processes notif payload -> calls the listeners
```

In order to receive the events even in closed state you need to define the listener in `Application#onCreate` method

The documents ([direct link to this topic](http://docs.pushe.co/docs/android/notification/notification-listener)) explicitly tells the user to implement a custom application.

Just define your application class :

```java
class MyApplication extends android.app.Application {
    
    @Override
    public void onCreate() {
        super.onCreate()
        // TODO define listener here
    }
}
```

and add the listener


> **What if I didn't want to implement a custom application?**  
> Even though it's a rare situation, this could be resolved using a `content provider` with a **lower priority in compare to Pushe's content provider** (which is 10 I think).
> **However**, the proper solution is to send local broadcast and implement a custom service in the library (which is not implemented in the library nor planned in the near future)

**Comment by greenreptile** [comment]
You are right. My code was in `onCreate` and problem was somewhere else. In fact I had started an Intent without proper flag. below code working like a charm now  :

```
intent.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
startActivity(intent);
```

With best.
